name: Lint code on change

on:
  push:
    paths:
      - "src/**.py"
  pull_request:
    paths:
      - "src/**.py"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ruff Linting
        uses: astral-sh/ruff-action@v3
        with:
          src: "src/"
